In [9]:
import numpy as np
import pandas as pd 

In [10]:
falsy_values = (0, False, None, '', [], {})

In [11]:
any(falsy_values)

False

In [12]:
np.nan


nan

In [13]:
3 + np.nan

nan

In [14]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])


In [15]:
a.sum()

nan

In [16]:
a.mean()

nan

In [19]:

a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [21]:

a.mean()

nan

In [22]:

a.sum()

nan

In [23]:

np.inf

inf

In [24]:
3 + np.inf

inf

In [25]:

np.inf / 3

inf

In [26]:
np.inf / np.inf

nan

In [ ]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=np.float)

In [28]:
b.sum()

nan

In [29]:
np.isnan(np.nan)

True

In [30]:

np.isinf(np.inf)

True

In [31]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [32]:
np.isnan(np.array([1,2,3,np.nan,np.inf,4]))

array([False, False, False,  True, False, False])

In [33]:
np.isinf(np.array([1,2,3,np.nan,np.inf,4]))

array([False, False, False, False,  True, False])

In [ ]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [34]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [35]:
a[np.isnan(a)]

array([nan, nan])

In [38]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [39]:
a[np.isfinite(a)].sum()

10.0